src/routes/web.php
<?php

use App\QuestionSelectGroup;
use App\Report;
use Illuminate\Support\Facades\Mail;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades;
use App\Mail\ReportMail;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/users/create_invitation', 'UsersController@create_invitation')->name('users.create_invitation')->middleware('permission:users.send_application_invite');
Route::post('/users/send_invitation', 'UsersController@send_invitation')->name('users.send_invitation')->middleware('permission:users.send_application_invite');

Route::resource('users', 'UsersController')->middleware('permission:users.resource_routes');

Route::post('/questions/activate_question', 'QuestionsController@activate_question')->name('questions.activate_question')->middleware('permission:questions.resource_routes');

Route::get('/questions/create_select_group', 'QuestionsController@create_select_group')->name('questions.create_select_group')->middleware('permission:question_selects.resource_routes');
Route::get('/questions/{question_select_group}/edit_select_group', 'QuestionsController@edit_select_group')->name('questions.edit_select_group')->middleware('permission:question_selects.resource_routes');
Route::post('/questions/store_question_select_group', 'QuestionsController@store_question_select_group')->name('questions.store_question_select_group')->middleware('permission:question_selects.resource_routes');
Route::put('/questions/{question_select_group}', 'QuestionsController@update_question_select_group')->name('questions.update_question_select_group')->middleware('permission:question_selects.resource_routes');

Route::resource('questions', 'QuestionsController')->middleware('permission:questions.resource_routes');

Route::get('/reports/index_own_reports', 'ReportsController@index_own_reports')->name('reports.index_own_reports')->middleware('permission:reports.list_own_reports');
Route::get('/reports/{report}/submit_report', 'ReportsController@submit_report')->name('reports.submit_report')->middleware('permission:reports.submit_report');
Route::get('/reports/create_employee_report', 'ReportsController@create_employee_report')->name('reports.create_employee_report')->middleware('permission:reports.create_employee_report');
Route::post('/reports/get_report_questions', 'ReportsController@get_report_questions')->name('reports.get_report_questions')->middleware('permission:reports.copy_admin_report_questions');
Route::post('/reports/get_report_employee_questions', 'ReportsController@get_report_employee_questions')->name('reports.get_report_employee_questions')->middleware('permission:reports.copy_employee_report_questions');
Route::get('/reports/change_submission_time', 'ReportsController@change_submission_time')->name('reports.change_submission_time')->middleware('permission:reports.change_report_submission_time');
Route::post('/reports/store_submission_time', 'ReportsController@store_submission_time')->name('reports.store_submission_time')->middleware('permission:reports.change_report_submission_time');
Route::post('/reports/approve_report', 'ReportsController@approve_report')->name('reports.approve_report')->middleware('permission:reports.approve_report');

Route::resource('reports', 'ReportsController')->middleware('permission:reports.resource_routes');

Route::resource('holidays', 'HolidaysController')->only([
    'index', 'create', 'store', 'destroy'
])->middleware('permission:holidays.resource_routes');

Route::get('/access_control/index', 'AccessControlController@index')->name('access_control.index')->middleware('permission:admin.application_access_control');
Route::post('/access_control/role_permissions', 'AccessControlController@role_permissions')->name('access_control.role_permissions')->middleware('permission:admin.application_access_control');
Route::post('/access_control/save_role_permission', 'AccessControlController@save_role_permission')->name('access_control.save_role_permission')->middleware('permission:admin.application_access_control');
Route::post('/access_control/create_role', 'AccessControlController@create_role')->name('access_control.create_role')->middleware('permission:admin.application_access_control');
Route::post('/access_control/store_role', 'AccessControlController@store_role')->name('access_control.store_role')->middleware('permission:admin.application_access_control');
Route::delete('/access_control/destroy_role/{role_id}', 'AccessControlController@destroy_role')->name('access_control.destroy_role')->middleware('permission:admin.application_access_control');
Route::post('/access_control/create_permission', 'AccessControlController@create_permission')->name('access_control.create_permission')->middleware('permission:admin.application_access_control');
Route::post('/access_control/store_permission', 'AccessControlController@store_permission')->name('access_control.store_permission')->middleware('permission:admin.application_access_control');
Route::delete('/access_control/destroy_permission/{permission_id}', 'AccessControlController@destroy_permission')->name('access_control.destroy_permission')->middleware('permission:admin.application_access_control');
Route::get('/access_control/{user}/edit_users_access_control', 'AccessControlController@edit_users_access_control')->name('access_control.edit_users_access_control')->middleware('permission:admin.users_access_control');
Route::post('/access_control/save_user_role', 'AccessControlController@save_user_role')->name('access_control.save_user_role')->middleware('permission:admin.users_access_control');
Route::post('/access_control/save_user_permission', 'AccessControlController@save_user_permission')->name('access_control.save_user_permission')->middleware('permission:admin.users_access_control');




Route::get('/roles', function (){
    \App\User::find(1)->assignRole('Super Admin');
});

src/app/Report.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    public function user(){
        return $this->belongsTo('App\User');
    }

    public function questions(){
        return $this->belongsToMany('App\Question', 'report_questions')
            ->withPivot('answer')
            ->withTimestamps();
    }

    public function statuses(){
        return $this->belongsToMany('App\Status', 'report_statuses')
            ->whereNull('report_statuses.deleted_at')
            ->withPivot('deleted_at')
            ->withTimestamps();
    }
}

src/app/Http/Controllers/ReportsController.php
<?php

namespace App\Http\Controllers;

use App\Mail\ReportMail;
use App\Question;
use App\QuestionSelectGroup;
use App\Report;
use App\ReportRemainderTime;
use App\ReportSubmissionTime;
use App\Status;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;

class ReportsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        $admin_reports = Report::where('type', 'questions')->orderBy('date_week', 'DESC')->get();
        $employee_reports = DB::table('reports')
            ->join('users', 'users.id', '=', 'reports.user_id')
            ->select('reports.*', 'users.name as user_name')
            ->where('reports.type', '=', 'answers')
            ->where('reports.submitted', '=', '1')
            ->orderBy('date_week', 'DESC')
            ->get();

        return view('reports.index',[
            'admin_reports' => $admin_reports,
            'users' => $users,
            'post' => '',
            'employee_reports' => $employee_reports
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $questions = Question::all();
        $reports = Report::where('submitted', '=', '1')->where('type', '=', 'questions')->orderBy('date_week', 'DESC')->get();

        return view('reports.create', [
            'questions' => $questions,
            'reports' => $reports
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->type == 'questions'){
            $request->validate([
                'date_week'  => 'required|unique:reports,date_week,NULL,id,type,questions'
            ]);
        }else{
            $request->validate([
                'date_week'  => 'required|unique:reports,date_week,NULL,id,user_id,' . Auth::id().',type,answers'

            ]);
        }

        $report = new Report;

        $report->name = $request->name;
        $report->type = $request->type;
        $report->date_week = $request->date_week;
        $report->submitted = $request->submitted;
        $report->user_id = Auth::id();

        $report->save();

        if ($request->submitted){
            $status = Status::where('code', 'submitted')->first();

            $report->statuses()->attach($status->id);
        }else{
            $status = Status::where('code', 'in_progress')->first();

            $report->statuses()->attach($status->id);
        }

        foreach ($request->question_id as $key => $value){
            if ($request->answer[$key]){
                $report->questions()->attach($value, array('answer'=>$request->answer[$key]));
            }else{
                $report->questions()->attach($value);
            }
            if ($report->submitted == 1){
                $question = Question::findOrFail($value);

                $question->currently_active = 1;

                $question->save();
            }
        }

        return redirect(route('reports.index_own_reports'))->withSuccessMessage('Report successfully created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Report  $report
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $report = Report::findOrFail($id);
        $report->questions = $report->questions()->get();
        foreach ($report->questions as $key => $value){
            if ($value->type == 'select'){
                $value->select_values = QuestionSelectGroup::findOrFail($value->question_select_group_id)->question_selects()->get();
            }
        }

        return view('reports.show', [
            'report'=>$report
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Report  $report
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $reports = Report::where('submitted', '=', '1')
            ->where('type', '=', 'questions')
            ->orderBy('date_week', 'DESC')
            ->get();

        $report = Report::findOrFail($id);

        if ($report->type == 'questions'){
            $questions = DB::select('SELECT questions.*,  report_questions.report_id
                    FROM questions
                    LEFT JOIN report_questions ON report_questions.question_id = questions.id AND report_questions.report_id= 8');

            return view('reports.edit', [
                'reports' => $reports,
                'report' => $report,
                'questions' => $questions
            ]);
        }else{
            $questions = $report->questions()->get();
            foreach ($questions as $key => $value){
                if ($value->type == 'select'){
                    $value->select_values = QuestionSelectGroup::findOrFail($value->question_select_group_id)->question_selects()->get();
                }
            }

            return view('reports.edit_employee_report', [
                'reports' => $reports,
                'report' => $report,
                'questions' => $questions
            ]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Report  $report
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $report = Report::findOrFail($id);

        $report->name = $request->name;
        $report->submitted = $request->submitted;

        $report->save();

        if ($request->submitted){
            DB::table('report_statuses')
                ->where('report_id', $id)
                ->where('deleted_at', '=',null)
                ->update(array('deleted_at' => now()));

            $status = Status::where('code', 'submitted')->first();

            $report->statuses()->attach($status->id);
        }

        $report->questions()->detach();
        foreach ($request->question_id as $key => $value){
            if ($request->answer[$key]){
                $report->questions()->attach($value, array('answer'=>$request->answer[$key]));
            }else{
                $report->questions()->attach($value);
            }
            if ($report->submitted == 1){
                $question = Question::findOrFail($value);

                $question->currently_active = 1;

                $question->save();
            }
        }

        return redirect(route('reports.index_own_reports'))->withSuccessMessage('Report successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Report  $report
     * @return \Illuminate\Http\Response
     */
    public function destroy(Report $report)
    {
        //
    }

    public function index_own_reports()
    {
        $employee_reports = DB::table('reports')
            ->join('users', 'users.id', '=', 'reports.user_id')
            ->join('report_statuses', 'report_statuses.report_id', '=', 'reports.id')
            ->join('statuses', 'statuses.id', '=', 'report_statuses.status_id')
            ->select('reports.*', 'users.name as user_name','statuses.name as status_name','statuses.code')
            ->where('reports.user_id', '=', Auth::id())
            ->where('report_statuses.deleted_at', '=', NULL)
            ->orderBy('date_week', 'DESC')
            ->get();

        return view('reports.index_own_reports',[
            'post' => '',
            'employee_reports' => $employee_reports
        ]);
    }

    public function submit_report($id){
        $report = Report::findOrFail($id);

        $report->submitted = 1;

        $report->save();

        DB::table('report_statuses')
            ->where('report_id', $id)
            ->where('deleted_at', '=',null)
            ->update(array('deleted_at' => now()));

        $status = Status::where('code', 'submitted')->first();

        $report->statuses()->attach($status->id);

        if($report->type == 'answers'){
            $questions = $report->questions()->get();
            foreach ($questions as $key => $value){
                if ($value->type == 'select'){
                    $value->select_values = QuestionSelectGroup::findOrFail($value->question_select_group_id)->question_selects()->get();
                }
            }

            $data = array(
                'view'=>'emails.report',
                'report'=>$report,
                'questions'=>$questions
            );

            Mail::to($report->user()->first()->email)->send(new ReportMail($data));
        }

        return redirect(route('reports.index_own_reports'))->withSuccessMessage('Report submitted successfully');
    }

    public function create_employee_report(){
        $reports = Report::where('submitted', '=', '1')
            ->where('type', '=', 'questions')
            ->orderBy('date_week', 'DESC')
            ->get();

        $report = Report::where('type', '=', 'questions')
            ->where('submitted', '=', 1)
            ->where('date_week', '=', date('Y-W', strtotime('friday this week')))
            ->first();

        $questions = '';
        if ($report){
            $questions = $report->questions()->get();
            foreach ($questions as $key => $value){
                if ($value->type == 'select'){
                    $value->select_values = QuestionSelectGroup::findOrFail($value->question_select_group_id)->question_selects()->get();
                }
            }
        }
        return view('reports.create_employee_report', [

src/resources/views/reports/answers.blade.php
@foreach($questions as $key => $value)
    <div class="form-row">
        <div class="form-group col-md-5">
            <input type="text" class="form-control" aria-label="Text input with checkbox" value="{{ $value->question }}" readonly>
            <input type="text" value="{{ $value->id }}" name="question_id[]" hidden>
        </div>
        <div class="form-group col-md-7">
            @if($value->type == 'input')
                <input type="text" name="answer[]" class="form-control" required value="{{ $value->pivot->answer }}">
            @elseif($value->type == 'textarea')
                <textarea class="form-control" name="answer[]" required>{{ $value->pivot->answer }}</textarea>
            @else
                <select class="form-control" name="answer[]" >
                    @foreach($value->select_values as $key1 => $value1)
                        <option <?= $value1->id == $value->pivot->answer ? 'selected' : '' ?> value="{{ $value1->id }}">{{ $value1->name }}</option>
                    @endforeach
                </select>
            @endif
        </div>
    </div>
@endforeach

src/resources/views/reports/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="row p-lg-2 pt-5">
        <div class="col-sm-8 offset-2">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Create report</h3>
                </div>

                    <div class="card-body">
                        <div class="form-row padding-top-8px">
                            <div class="form-group col-sm-10 offset-1">
                                <select id="copy_from_week_admin_reports" class="form-control" data-url="{{ route('reports.get_report_questions') }}">
                                    <option value="0">Copy questions from previous weeks</option>
                                    @foreach($reports as $key => $value)
                                        <option value="{{ $value->id }}">{{ $value->date_week.' | '.$value->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-sm-12">
                                <hr>
                            </div>
                        </div>
                        <form method="post" action="{{route('reports.store')  }}" id="create_report_form">
                            @csrf
                        <div class="form-row">
                            <div class="form-group col-sm-6">
                                <label for="report_name">Report name:</label>
                                <input type="text" class="form-control" name="name" id="report_name" autocomplete="off">
                            </div>
                            <div class="form-group col-sm-6">
                                <label for="report_date">Year-week(default next week):</label>
                                <input type="text" class="form-control date-year-week @error('date_week') is-invalid @enderror" name="date_week" id="report_date" autocomplete="off" value="{{ date('Y-W', strtotime('friday next week')) }}"/>
                                @error('date_week')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                                <input name="type" value="questions" hidden>
                                <input name="submitted" value="0" id="report_submitted" hidden>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-sm-12">
                                <hr>
                                <label>Questions:</label>
                            </div>
                        </div>
                        @include('reports.questions')
                        <div class="card-footer">
                            <button type="button" class="btn btn-primary float-right m-1" id="submit_report">Submit</button>
                            <button type="button" class="btn btn-primary float-right m-1" id="create_report">Save</button>
                        </div>
                        </form>
                    </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>
@endsection

src/resources/views/reports/create_employee_report.blade.php
@extends('layouts.master')

@section('content')
    <div class="row p-lg-2 pt-5">
        <div class="col-sm-10 offset-1">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Create report</h3>
                </div>
                <div class="card-body">
                    <div class="form-row padding-top-8px">
                        <div class="form-group col-sm-10 offset-1">
                            <select id="copy_from_week_employee_reports" class="form-control"
                                    data-url="{{ route('reports.get_report_employee_questions') }}">
                                <option value="{{ date('Y-W', strtotime('friday this week')) }}">Fill out report for
                                    previous weeks
                                </option>
                                @foreach($reports as $key => $value)
                                    @if($value->date_week < date('Y-W', strtotime('friday this week')))
                                        <option
                                            value="{{ $value->date_week }}">{{ $value->date_week.' | '.$value->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-sm-12">
                            <hr>
                        </div>
                    </div>
                    @if($questions)
                        <form method="post" action="{{ route('reports.store') }}" id="create_report_form">
                            @csrf
                            <div class="form-row">
                                <div class="form-group col-sm-6">
                                    <label for="report_name">Report name:</label>
                                    <input type="text" class="form-control" name="name" id="report_name"
                                           autocomplete="off">
                                </div>
                                <div class="form-group col-sm-6">
                                    <label for="report_date">Year-week(default current week):</label>
                                    <input type="text" class="form-control @error('date_week') is-invalid @enderror"
                                           name="date_week" id="report_date" autocomplete="off"
                                           value="{{ date('Y-W', strtotime('friday this week')) }}" readonly/>
                                    @error('date_week')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                    <input name="type" value="answers" hidden>
                                    <input name="submitted" value="0" id="report_submitted" hidden>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-sm-12">
                                    <hr>
                                    <label>Questions:</label>
                                </div>
                            </div>
                            <div id="report_answers_div">
                                @include('reports.answers')
                            </div>
                            <div class="card-footer">
                                <button type="button" class="btn btn-primary float-right m-1" id="submit_report">
                                    Submit
                                </button>
                                <button type="button" class="btn btn-primary float-right m-1" id="create_report">Save
                                </button>
                            </div>
                            @else
                                <div class="row">
                                    <div class="col-sm-8 offset-2">
                                        <h2 class="text-danger font-weight-bold">We are sorry to inform you that the
                                            admin hasn't submitted a valid form for this week yet. Please try again
                                            later.</h2>
                                    </div>
                                </div>
                            @endif
                        </form>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>
@endsection

src/resources/views/reports/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="row p-lg-2 pt-5">
        <div class="col-sm-12">
            <div class="card card-dark">
                <div class="card-header">
                    <h3 class="card-title">Edit report</h3>
                </div>
                <div class="card-body">
                    <div class="form-row padding-top-8px">
                        <div class="form-group col-md-10 offset-1">
                            <select id="copy_from_week_admin_reports" class="form-control"
                                    data-url="{{ route('reports.get_report_questions') }}">
                                <option value="0">Copy questions from previous weeks</option>
                                @foreach($reports as $key => $value)
                                    <option value="{{ $value->id }}">{{ $value->date_week.' | '.$value->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-sm-12">
                            <hr>
                        </div>
                    </div>
                    <form method="post" action="{{route('reports.update', ['report'=>$report->id])  }}"
                          id="create_report_form">
                        @method('patch')
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="report_name">Report name:</label>
                                <input type="text" class="form-control" name="name" id="report_name" autocomplete="off"
                                       value="{{ $report->name }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="report_date">Year-week:</label>
                                <input type="text" class="form-control date-year-week" name="date_week" id="report_date"
                                       autocomplete="off" value="{{ $report->date_week }}" readonly/>
                                <input name="type" value="questions" hidden>
                                <input name="submitted" value="{{ $value->submitted }}" id="report_submitted" hidden>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <hr>
                                <label>Questions:</label>
                            </div>
                        </div>
                        @include('reports.questions_edit')
                        <div class="card-footer">
                            <button type="button" class="btn btn-primary float-right m-1" id="submit_report">Submit
                            </button>
                            <button type="button" class="btn btn-primary float-right m-1" id="create_report">Save
                            </button>
                        </div>
                    </form>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>

@endsection

src/resources/views/reports/questions.blade.php
@foreach($questions as $key => $value)
    <div class="form-row">
        <div class="form-group col-md-12">
            <div class="input-group mb-3">
                <input type="text" class="form-control" aria-label="Text input with checkbox" value="{{ $value->question }}" readonly>
                <div class="input-group-append">
                    <div class="input-group-text">
                        <input type="checkbox" aria-label="Checkbox for following text input" value="{{ $value->id }}" name="question_id[]" id="question_checkbox_{{ $value->id }}" {{ $value->currently_active ? 'checked' : '' }} class="questions-checkboxes">
                    </div>
                </div>
            </div>
        </div>
    </div>
@endforeach

src/resources/views/reports/questions_edit.blade.php
@foreach($questions as $key => $value)
    <div class="form-row">
        <div class="form-group col-md-12">
            <div class="input-group mb-3">
                <input type="text" class="form-control" aria-label="Text input with checkbox" value="{{ $value->question }}" readonly>
                <div class="input-group-append">
                    <div class="input-group-text">
                        <input type="checkbox" aria-label="Checkbox for following text input" value="{{ $value->id }}" name="question_id[]" id="question_checkbox_{{ $value->id }}" {{ isset($value->report_id) ? 'checked' : '' }} class="questions-checkboxes">
                    </div>
                </div>
            </div>
        </div>
    </div>
@endforeach