src/routes/web.php
<?php

use App\QuestionSelectGroup;
use App\Report;
use Illuminate\Support\Facades\Mail;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades;
use App\Mail\ReportMail;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/users/create_invitation', 'UsersController@create_invitation')->name('users.create_invitation')->middleware('permission:users.send_application_invite');
Route::post('/users/send_invitation', 'UsersController@send_invitation')->name('users.send_invitation')->middleware('permission:users.send_application_invite');

Route::resource('users', 'UsersController')->middleware('permission:users.resource_routes');

Route::post('/questions/activate_question', 'QuestionsController@activate_question')->name('questions.activate_question')->middleware('permission:questions.resource_routes');

Route::get('/questions/create_select_group', 'QuestionsController@create_select_group')->name('questions.create_select_group')->middleware('permission:question_selects.resource_routes');
Route::get('/questions/{question_select_group}/edit_select_group', 'QuestionsController@edit_select_group')->name('questions.edit_select_group')->middleware('permission:question_selects.resource_routes');
Route::post('/questions/store_question_select_group', 'QuestionsController@store_question_select_group')->name('questions.store_question_select_group')->middleware('permission:question_selects.resource_routes');
Route::put('/questions/{question_select_group}', 'QuestionsController@update_question_select_group')->name('questions.update_question_select_group')->middleware('permission:question_selects.resource_routes');

Route::resource('questions', 'QuestionsController')->middleware('permission:questions.resource_routes');

Route::get('/reports/index_own_reports', 'ReportsController@index_own_reports')->name('reports.index_own_reports')->middleware('permission:reports.list_own_reports');
Route::get('/reports/{report}/submit_report', 'ReportsController@submit_report')->name('reports.submit_report')->middleware('permission:reports.submit_report');
Route::get('/reports/create_employee_report', 'ReportsController@create_employee_report')->name('reports.create_employee_report')->middleware('permission:reports.create_employee_report');
Route::post('/reports/get_report_questions', 'ReportsController@get_report_questions')->name('reports.get_report_questions')->middleware('permission:reports.copy_admin_report_questions');
Route::post('/reports/get_report_employee_questions', 'ReportsController@get_report_employee_questions')->name('reports.get_report_employee_questions')->middleware('permission:reports.copy_employee_report_questions');
Route::get('/reports/change_submission_time', 'ReportsController@change_submission_time')->name('reports.change_submission_time')->middleware('permission:reports.change_report_submission_time');
Route::post('/reports/store_submission_time', 'ReportsController@store_submission_time')->name('reports.store_submission_time')->middleware('permission:reports.change_report_submission_time');
Route::post('/reports/approve_report', 'ReportsController@approve_report')->name('reports.approve_report')->middleware('permission:reports.approve_report');

Route::resource('reports', 'ReportsController')->middleware('permission:reports.resource_routes');

Route::resource('holidays', 'HolidaysController')->only([
    'index', 'create', 'store', 'destroy'
])->middleware('permission:holidays.resource_routes');

Route::get('/access_control/index', 'AccessControlController@index')->name('access_control.index')->middleware('permission:admin.application_access_control');
Route::post('/access_control/role_permissions', 'AccessControlController@role_permissions')->name('access_control.role_permissions')->middleware('permission:admin.application_access_control');
Route::post('/access_control/save_role_permission', 'AccessControlController@save_role_permission')->name('access_control.save_role_permission')->middleware('permission:admin.application_access_control');
Route::post('/access_control/create_role', 'AccessControlController@create_role')->name('access_control.create_role')->middleware('permission:admin.application_access_control');
Route::post('/access_control/store_role', 'AccessControlController@store_role')->name('access_control.store_role')->middleware('permission:admin.application_access_control');
Route::delete('/access_control/destroy_role/{role_id}', 'AccessControlController@destroy_role')->name('access_control.destroy_role')->middleware('permission:admin.application_access_control');
Route::post('/access_control/create_permission', 'AccessControlController@create_permission')->name('access_control.create_permission')->middleware('permission:admin.application_access_control');
Route::post('/access_control/store_permission', 'AccessControlController@store_permission')->name('access_control.store_permission')->middleware('permission:admin.application_access_control');
Route::delete('/access_control/destroy_permission/{permission_id}', 'AccessControlController@destroy_permission')->name('access_control.destroy_permission')->middleware('permission:admin.application_access_control');
Route::get('/access_control/{user}/edit_users_access_control', 'AccessControlController@edit_users_access_control')->name('access_control.edit_users_access_control')->middleware('permission:admin.users_access_control');
Route::post('/access_control/save_user_role', 'AccessControlController@save_user_role')->name('access_control.save_user_role')->middleware('permission:admin.users_access_control');
Route::post('/access_control/save_user_permission', 'AccessControlController@save_user_permission')->name('access_control.save_user_permission')->middleware('permission:admin.users_access_control');




Route::get('/roles', function (){
    \App\User::find(1)->assignRole('Super Admin');
});

src/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Config;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function reports(){
        return $this->hasMany('App\Reports');
    }

    public function routeNotificationFor($driver, $notification = null)
    {
        return Config::get('constants.slack_webhook');
    }
}

src/app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;


use App\Mail\ReportMail;
use App\User;
use DebugBar\DebugBar;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Validation\Rule;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $users = User::all();
        //\Debugbar::info($users);

        return view('users.index', [
            'post' => '',
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        $user = new User;

        $user->email = request('email');
        $user->name = request('name');
        $user->password = Hash::make(request('password'));

        $user->save();

        return redirect(route('users.index'))->withSuccessMessage('User successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('users.edit', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($id)],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        $user = User::findOrFail($id);

        $user->email = request('email');
        $user->name = request('name');
        $user->password = Hash::make(request('password'));

        $user->save();


        return redirect(route('users.index'))->withSuccessMessage('User successfully edited!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::findOrFail($id)->delete();

        return redirect(route('users.index'))->withSuccessMessage('User successfully deleted!');
    }

    public function create_invitation()
    {
        return view('users.create_invitation');
    }

    public function send_invitation(Request $request)
    {
        $request->validate([
            'email'=>'email'
        ]);

        $data['view'] = 'emails.send_invitation';
        $data['body'] = $request->body;

        Mail::to($request->email)->send(new ReportMail($data));

        return redirect(route('home'))->withSuccessMessage('Invitation sent successfully!');
    }

}

src/resources/views/users/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="row p-lg-2 pt-5">
        <div class="col-sm-8 offset-2">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Create user</h3>
                </div>
                <form method="post" action="{{route('users.store')  }}">
                    @csrf
                    <div class="card-body">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="user_name">Name:</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror"
                                       id="user_name" name="name" required="required">
                                @error('name')
                                <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label for="user_email">Email</label>
                                <input type="email" class="form-control @error('email') is-invalid @enderror"
                                       id="user_email" name="email" required="required">
                                @error('email')
                                <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="user_password">Password:</label>
                                <input type="password" class="form-control @error('password') is-invalid @enderror"
                                       id="user_password" name="password" required="required">
                                @error('password')
                                <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label for="user_confirm_passwords">Confirm password:</label>
                                <input type="password" class="form-control" id="user_confirm_passwords"
                                       name="password_confirmation"
                                       required="required">
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary float-right">Create</button>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </form>
            </div>
        </div>
    </div>
@endsection

src/resources/views/users/create_invitation.blade.php
@extends('layouts.master')

@section('content')
        <div class="row p-lg-2 pt-5">
            <div class="col-sm-8 offset-2">
                <div class="card card-secondary">
                    <div class="card-header">
                        <h3 class="card-title">Invitation mail</h3>
                    </div>
                    <form method="post" action="{{route('users.send_invitation')  }}">
                        @csrf
                        <div class="card-body">
                            <div class="form-row">
                                <div class="form-group col-md-8 offset-2">
                                    <label for="user_email">Email:</label>
                                    <input type="email" class="form-control @error('email') is-invalid @enderror"
                                           id="user_email" name="email" required="required">
                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-8 offset-2">
                                    <label for="email_content">Content:</label>
                                    <textarea class="form-control" id="email_content" name="body"></textarea>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary float-right">Send email</button>
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </form>
                </div>
            </div>
        </div>
@endsection

src/resources/views/users/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="row p-lg-2 pt-5">
        <div class="col-sm-8 offset-2">
            <div class="card card-dark">
                <div class="card-header">
                    <h3 class="card-title">Edit user</h3>
                </div>
                <form method="post" action="{{route('users.update', ['user'=>$user])  }}">
                    @csrf
                    <div class="card-body">
                        @method('patch')
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="user_name">Name:</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" id="user_name" name="name" required="required" value="{{ $user->name }}">
                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label for="user_email">Email</label>
                                <input type="email" class="form-control @error('email') is-invalid @enderror" id="user_email" name="email" required="required" value="{{ $user->email }}">
                                @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="user_password">Password:</label>
                                <input type="password" class="form-control @error('password') is-invalid @enderror" id="user_password" name="password" required="required">
                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                            <div class="form-group col-md-6">
                                <label for="user_confirm_passwords">Confirm password:</label>
                                <input type="password" class="form-control" id="user_confirm_passwords" name="password_confirmation"
                                       required="required">
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary float-right">Edit</button>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </form>
            </div>
        </div>
    </div>
@endsection

src/resources/views/users/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="row pt-5">
        <div class="col-sm-8 offset-2">
            <table class="table jquery-datatable">
                <thead class="thead-dark ">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Created at</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                <?php $i = 1; foreach($users as $key => $value){ ?>
                <tr>
                    <th scope="row"><?= $i ?></th>
                    <td><?= $value->name ?></td>
                    <td><?= $value->email ?></td>
                    <td><?= $value->created_at ?></td>
                    <td><div class="d-inline-flex"><a href="{{ route('users.edit', ['user' => $value]) }}" class="btn btn-info">Edit</a>
                        <form method="POST" action="{{ route('users.destroy', ['user' => $value]) }}">
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger delete-confirmation ml-2" type="button">Delete</button>
                        </form>
                        <a class="btn btn-primary  ml-2" href="{{ route('access_control.edit_users_access_control', ['user' => $value->id]) }}">Permissions</a>
                        </div>
                    </td>
                </tr>
                <?php $i++; } ?>
                </tbody>
            </table>
        </div>
    </div>
@endsection