src/routes/web.php
<?php

use App\QuestionSelectGroup;
use App\Report;
use Illuminate\Support\Facades\Mail;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades;
use App\Mail\ReportMail;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/users/create_invitation', 'UsersController@create_invitation')->name('users.create_invitation')->middleware('permission:users.send_application_invite');
Route::post('/users/send_invitation', 'UsersController@send_invitation')->name('users.send_invitation')->middleware('permission:users.send_application_invite');

Route::resource('users', 'UsersController')->middleware('permission:users.resource_routes');

Route::post('/questions/activate_question', 'QuestionsController@activate_question')->name('questions.activate_question')->middleware('permission:questions.resource_routes');

Route::get('/questions/create_select_group', 'QuestionsController@create_select_group')->name('questions.create_select_group')->middleware('permission:question_selects.resource_routes');
Route::get('/questions/{question_select_group}/edit_select_group', 'QuestionsController@edit_select_group')->name('questions.edit_select_group')->middleware('permission:question_selects.resource_routes');
Route::post('/questions/store_question_select_group', 'QuestionsController@store_question_select_group')->name('questions.store_question_select_group')->middleware('permission:question_selects.resource_routes');
Route::put('/questions/{question_select_group}', 'QuestionsController@update_question_select_group')->name('questions.update_question_select_group')->middleware('permission:question_selects.resource_routes');

Route::resource('questions', 'QuestionsController')->middleware('permission:questions.resource_routes');

Route::get('/reports/index_own_reports', 'ReportsController@index_own_reports')->name('reports.index_own_reports')->middleware('permission:reports.list_own_reports');
Route::get('/reports/{report}/submit_report', 'ReportsController@submit_report')->name('reports.submit_report')->middleware('permission:reports.submit_report');
Route::get('/reports/create_employee_report', 'ReportsController@create_employee_report')->name('reports.create_employee_report')->middleware('permission:reports.create_employee_report');
Route::post('/reports/get_report_questions', 'ReportsController@get_report_questions')->name('reports.get_report_questions')->middleware('permission:reports.copy_admin_report_questions');
Route::post('/reports/get_report_employee_questions', 'ReportsController@get_report_employee_questions')->name('reports.get_report_employee_questions')->middleware('permission:reports.copy_employee_report_questions');
Route::get('/reports/change_submission_time', 'ReportsController@change_submission_time')->name('reports.change_submission_time')->middleware('permission:reports.change_report_submission_time');
Route::post('/reports/store_submission_time', 'ReportsController@store_submission_time')->name('reports.store_submission_time')->middleware('permission:reports.change_report_submission_time');
Route::post('/reports/approve_report', 'ReportsController@approve_report')->name('reports.approve_report')->middleware('permission:reports.approve_report');

Route::resource('reports', 'ReportsController')->middleware('permission:reports.resource_routes');

Route::resource('holidays', 'HolidaysController')->only([
    'index', 'create', 'store', 'destroy'
])->middleware('permission:holidays.resource_routes');

Route::get('/access_control/index', 'AccessControlController@index')->name('access_control.index')->middleware('permission:admin.application_access_control');
Route::post('/access_control/role_permissions', 'AccessControlController@role_permissions')->name('access_control.role_permissions')->middleware('permission:admin.application_access_control');
Route::post('/access_control/save_role_permission', 'AccessControlController@save_role_permission')->name('access_control.save_role_permission')->middleware('permission:admin.application_access_control');
Route::post('/access_control/create_role', 'AccessControlController@create_role')->name('access_control.create_role')->middleware('permission:admin.application_access_control');
Route::post('/access_control/store_role', 'AccessControlController@store_role')->name('access_control.store_role')->middleware('permission:admin.application_access_control');
Route::delete('/access_control/destroy_role/{role_id}', 'AccessControlController@destroy_role')->name('access_control.destroy_role')->middleware('permission:admin.application_access_control');
Route::post('/access_control/create_permission', 'AccessControlController@create_permission')->name('access_control.create_permission')->middleware('permission:admin.application_access_control');
Route::post('/access_control/store_permission', 'AccessControlController@store_permission')->name('access_control.store_permission')->middleware('permission:admin.application_access_control');
Route::delete('/access_control/destroy_permission/{permission_id}', 'AccessControlController@destroy_permission')->name('access_control.destroy_permission')->middleware('permission:admin.application_access_control');
Route::get('/access_control/{user}/edit_users_access_control', 'AccessControlController@edit_users_access_control')->name('access_control.edit_users_access_control')->middleware('permission:admin.users_access_control');
Route::post('/access_control/save_user_role', 'AccessControlController@save_user_role')->name('access_control.save_user_role')->middleware('permission:admin.users_access_control');
Route::post('/access_control/save_user_permission', 'AccessControlController@save_user_permission')->name('access_control.save_user_permission')->middleware('permission:admin.users_access_control');




Route::get('/roles', function (){
    \App\User::find(1)->assignRole('Super Admin');
});

src/app/Holiday.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Holiday extends Model
{
    //
}

src/app/Http/Controllers/HolidaysController.php
<?php

namespace App\Http\Controllers;

use App\Holiday;
use Illuminate\Http\Request;

class HolidaysController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $holidays = Holiday::where('year', '=', date('Y'))
            ->orWhere('type', '=', 'global')
            ->orderBy('month_day')
            ->get();

        return view('holidays.index', [
            'holidays' => $holidays
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('holidays.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (isset($request->date) && !empty($request->date)){
            foreach ($request->date as $key => $value){
                $holiday = new Holiday;

                $holiday->name = $request->name[$key];
                $holiday->month_day = date('m-d', strtotime($value));
                $holiday->year = date('Y', strtotime($value));
                $holiday->type = $request->type[$key];

                $holiday->save();
            }
        }else{
            return redirect(route('holidays.create'));
        }

        return redirect(route('holidays.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Holiday::findOrFail($id)->delete();

        return redirect(route('holidays.index'));
    }
}

src/resources/views/holidays/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="row p-lg-2 pt-5">
        <div class="col-sm-10 offset-1">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Add holiday</h3>
                </div>
                <form method="post" action="{{route('holidays.store')  }}">
                    @csrf
                    <div class="card-body">
                        <div class="form-row">
                            <div class="form-group col-md-5">
                                <label for="holiday_name">Holiday name:</label>
                                <input type="text" class="form-control" id="holiday_name" autocomplete="off">
                            </div>
                            <div class="form-group col-md-4">
                                <label for="holiday_date">Date:</label>
                                <input type="text" class="form-control date-year-month-day" id="holiday_date" required autocomplete="off"/>
                            </div>
                            <div class="form-group col-md-3">
                                <label for="holiday_type">Type:</label>
                                <select class="form-control" id="holiday_type">
                                    <option value="global">Global</option>
                                    <option value="yearly">Yearly</option>
                                </select>
                            </div>
                        </div>
                        <hr>
                        <div id="add_holidays_div">

                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary float-right m-1">Save</button>
                            <button type="button" class="btn btn-primary float-right m-1" id="add_holidays">Add</button>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </form>
            </div>
        </div>
    </div>
@endsection

src/resources/views/holidays/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="row">
        <div class="col-sm-8 offset-2">
            <h2 class="pt-5 pb-2">Holidays({{ date('Y') }})</h2>
            <table class="table jquery-datatable">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Date</th>
                    <th scope="col">Type</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                <?php $i = 1;  foreach($holidays as $key => $value){ ?>
                <tr>
                    <td>{{ $i }}</td>
                    <td>{{ $value->name }}</td>
                    <td>{{ date('Y').'-'.$value->month_day }}</td>
                    <td>{{ ucfirst($value->type) }}</td>
                    <td>
                        <form method="POST" action="{{ route('holidays.destroy', ['holiday' => $value->id]) }}">
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger delete-confirmation" type="button">Delete</button>
                        </form>
                    </td>
                </tr>
                <?php $i++; } ?>
                </tbody>
            </table>
        </div>
    </div>
@endsection