src/routes/web.php
<?php

use App\QuestionSelectGroup;
use App\Report;
use Illuminate\Support\Facades\Mail;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades;
use App\Mail\ReportMail;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/users/create_invitation', 'UsersController@create_invitation')->name('users.create_invitation')->middleware('permission:users.send_application_invite');
Route::post('/users/send_invitation', 'UsersController@send_invitation')->name('users.send_invitation')->middleware('permission:users.send_application_invite');

Route::resource('users', 'UsersController')->middleware('permission:users.resource_routes');

Route::post('/questions/activate_question', 'QuestionsController@activate_question')->name('questions.activate_question')->middleware('permission:questions.resource_routes');

Route::get('/questions/create_select_group', 'QuestionsController@create_select_group')->name('questions.create_select_group')->middleware('permission:question_selects.resource_routes');
Route::get('/questions/{question_select_group}/edit_select_group', 'QuestionsController@edit_select_group')->name('questions.edit_select_group')->middleware('permission:question_selects.resource_routes');
Route::post('/questions/store_question_select_group', 'QuestionsController@store_question_select_group')->name('questions.store_question_select_group')->middleware('permission:question_selects.resource_routes');
Route::put('/questions/{question_select_group}', 'QuestionsController@update_question_select_group')->name('questions.update_question_select_group')->middleware('permission:question_selects.resource_routes');

Route::resource('questions', 'QuestionsController')->middleware('permission:questions.resource_routes');

Route::get('/reports/index_own_reports', 'ReportsController@index_own_reports')->name('reports.index_own_reports')->middleware('permission:reports.list_own_reports');
Route::get('/reports/{report}/submit_report', 'ReportsController@submit_report')->name('reports.submit_report')->middleware('permission:reports.submit_report');
Route::get('/reports/create_employee_report', 'ReportsController@create_employee_report')->name('reports.create_employee_report')->middleware('permission:reports.create_employee_report');
Route::post('/reports/get_report_questions', 'ReportsController@get_report_questions')->name('reports.get_report_questions')->middleware('permission:reports.copy_admin_report_questions');
Route::post('/reports/get_report_employee_questions', 'ReportsController@get_report_employee_questions')->name('reports.get_report_employee_questions')->middleware('permission:reports.copy_employee_report_questions');
Route::get('/reports/change_submission_time', 'ReportsController@change_submission_time')->name('reports.change_submission_time')->middleware('permission:reports.change_report_submission_time');
Route::post('/reports/store_submission_time', 'ReportsController@store_submission_time')->name('reports.store_submission_time')->middleware('permission:reports.change_report_submission_time');
Route::post('/reports/approve_report', 'ReportsController@approve_report')->name('reports.approve_report')->middleware('permission:reports.approve_report');

Route::resource('reports', 'ReportsController')->middleware('permission:reports.resource_routes');

Route::resource('holidays', 'HolidaysController')->only([
    'index', 'create', 'store', 'destroy'
])->middleware('permission:holidays.resource_routes');

Route::get('/access_control/index', 'AccessControlController@index')->name('access_control.index')->middleware('permission:admin.application_access_control');
Route::post('/access_control/role_permissions', 'AccessControlController@role_permissions')->name('access_control.role_permissions')->middleware('permission:admin.application_access_control');
Route::post('/access_control/save_role_permission', 'AccessControlController@save_role_permission')->name('access_control.save_role_permission')->middleware('permission:admin.application_access_control');
Route::post('/access_control/create_role', 'AccessControlController@create_role')->name('access_control.create_role')->middleware('permission:admin.application_access_control');
Route::post('/access_control/store_role', 'AccessControlController@store_role')->name('access_control.store_role')->middleware('permission:admin.application_access_control');
Route::delete('/access_control/destroy_role/{role_id}', 'AccessControlController@destroy_role')->name('access_control.destroy_role')->middleware('permission:admin.application_access_control');
Route::post('/access_control/create_permission', 'AccessControlController@create_permission')->name('access_control.create_permission')->middleware('permission:admin.application_access_control');
Route::post('/access_control/store_permission', 'AccessControlController@store_permission')->name('access_control.store_permission')->middleware('permission:admin.application_access_control');
Route::delete('/access_control/destroy_permission/{permission_id}', 'AccessControlController@destroy_permission')->name('access_control.destroy_permission')->middleware('permission:admin.application_access_control');
Route::get('/access_control/{user}/edit_users_access_control', 'AccessControlController@edit_users_access_control')->name('access_control.edit_users_access_control')->middleware('permission:admin.users_access_control');
Route::post('/access_control/save_user_role', 'AccessControlController@save_user_role')->name('access_control.save_user_role')->middleware('permission:admin.users_access_control');
Route::post('/access_control/save_user_permission', 'AccessControlController@save_user_permission')->name('access_control.save_user_permission')->middleware('permission:admin.users_access_control');




Route::get('/roles', function (){
    \App\User::find(1)->assignRole('Super Admin');
});

src/app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    public function question_select_group(){
        return $this->belongsTo('App\QuestionSelectGroup');
    }

    public function reports(){
        return $this->belongsToMany('App\Report', 'report_questions')->withPivot('answer')->withTimestamps();
    }
}

src/app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use App\QuestionSelect;
use App\QuestionSelectGroup;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use DebugBar\DebugBar;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Validation\Rule;

class QuestionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $questions = DB::table('questions')
            ->leftJoin('question_select_groups', 'question_select_groups.id', '=', 'questions.question_select_group_id')
            ->select('questions.*', 'question_select_groups.name')
            ->get();
        $questionGroups = QuestionSelectGroup::all();
        $active_questions = Question::where('currently_active', 1)->count();


        return view('questions.index', [
            'questions' => $questions,
            'active_questions' => $active_questions,
            'question_groups' => $questionGroups
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $questionGroups = QuestionSelectGroup::all();

        return view('questions.create', [
            'question_groups' => $questionGroups
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $question = new Question;

        $question->question = request('question');
        $question->type = request('type');
        if (request('question_select_group_id'))
            $question->question_select_group_id = request('question_select_group_id');

        $question->save();

        return redirect(route('questions.index'))->withSuccessMessage('Question successfully created!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $question = Question::findOrFail($id);
        $questionGroups = QuestionSelectGroup::all();

        return view('questions.edit', [
            'question' => $question,
            'question_groups' => $questionGroups
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $question = Question::findOrFail($id);

        $question->question = $request->question;
        $question->type = $request->type;
        if ($request->question_select_group_id)
            $question->question_select_group_id = $request->question_select_group_id;
        else
            $question->question_select_group_id = null;

        $question->save();

        return redirect(route('questions.index'))->withSuccessMessage('Question successfully created!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $question = Question::findOrFail($id);

        $question->currently_active = 0;

        $question->save();

        return redirect(route('questions.index'))->withSuccessMessage('Question deactivated successfully!');
    }

    public function activate_question(Request $request)
    {
        $question = Question::findOrFail(request('id'));

        $question->currently_active = 1;

        $question->save();

        Alert::toast('Question activated successfully!', 'success');
    }


    public function create_select_group()
    {
        return view('questions.create_select_group');
    }

    public function store_question_select_group(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'code' => ['required', 'string', 'max:255', 'unique:question_select_groups'],
        ]);

        if (!isset($request->question_select_label) || count($request->question_select_label) < 2) {
            Alert::error('Error', 'Enter atleast two values for the select!');

            return redirect(route('questions.create_select_group'));
        }

        $question_group = new QuestionSelectGroup;

        $question_group->name = $request->name;
        $question_group->code = $request->code;

        $question_group->save();

        foreach ($request->question_select_label as $key => $value) {
            $question_select = new QuestionSelect;

            $question_select->name = $value;
            $question_select->value = $request->question_select_value[$key];
            $question_select->question_select_group_id = $question_group->id;

            $question_select->save();
        }

        return redirect(route('questions.index'))->withSuccessMessage('Question select group added successfully!');
    }

    public function edit_select_group($id)
    {
        $question_group = QuestionSelectGroup::findOrFail($id);
        $question_selects = QuestionSelect::where('question_select_group_id', $id)->orderBy('value')->get();

        return view('questions.edit_select_group', [
            'question_group' => $question_group,
            'question_selects' => $question_selects,
        ]);
    }

    public function update_question_select_group(Request $request, $id)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'code' => ['required', 'string', 'max:255', Rule::unique('question_select_groups')->ignore($id)],
        ]);

        $question_group = QuestionSelectGroup::findOrFail($id);

        $question_group->name = $request->name;
        $question_group->code = $request->code;

        $question_group->save();

        foreach ($request->question_select_label as $key => $value) {
            $question_select = new QuestionSelect;

            $question_select->name = $value;
            $question_select->value = $request->question_select_value[$key];
            $question_select->question_select_group_id = $question_group->id;

            $question_select->save();
        }

        return redirect(route('questions.index'))->withSuccessMessage('Question select group updated successfully!');
    }


}

src/resources/views/questions/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="row p-lg-2 pt-5">
        <div class="col-sm-8 offset-2">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Add question</h3>
                </div>

                <div class="card-body">
                    <form method="post" action="{{route('questions.store')  }}">
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-12" >
                                <label for="question">Question:</label>
                                <input type="text" class="form-control" name="question" id="question" required="required">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="question_type">Type:</label>
                                <select class="form-control" id="question_type" name="type">
                                    <option value="input">Input</option>
                                    <option value="select">Select</option>
                                    <option value="textarea">Textarea</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-row" id="question_select_group_div" hidden>
                            <div class="form-group col-md-12">
                                <label for="question_select_group">Group:</label>
                                <select class="form-control" id="question_select_group" name="question_select_group_id" disabled required>
                                    @foreach($question_groups as $key => $value)
                                        <option value="<?= $value->id ?>"><?= $value->name ?></option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary float-right">Add</button>
                        </div>
                    </form>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>
@endsection

src/resources/views/questions/create_select_group.blade.php
@extends('layouts.master')

@section('content')
    <div class="row p-lg-2 pt-5">
        <div class="col-sm-8 offset-2">
            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Create question select group</h3>
                </div>

                <div class="card-body">
                    <form method="post" action="{{route('questions.store_question_select_group')  }}">
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="question_group_name">Name:</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                                       id="question_group_name" required="required">
                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="question_group_code">Code:</label>
                                <input type="text" class="form-control @error('code') is-invalid @enderror" name="code"
                                       id="question_group_code" required="required">
                                @error('code')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <hr>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-5">
                                <input type="text" class="form-control" id="question_select_name" placeholder="Label">
                            </div>
                            <div class="form-group col-md-5">
                                <input type="text" class="form-control" id="question_select_value" placeholder="Value">
                            </div>
                            <div class="form-group col-md-2">
                                <button class="btn btn-outline-primary" id="add_question_select" type="button">Add
                                </button>
                            </div>
                        </div>
                        <div class="form-row" id="add_question_selects_div">
                            <div class="form-group col-md-12">
                                <hr>
                            </div>
                        </div>
                        <div class="form-row" id="add_question_selects_div">
                            <div class="form-group col-md-12">
                                <hr>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary float-right">Create</button>
                        </div>
                    </form>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>

@endsection

src/resources/views/questions/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="row p-lg-2 pt-5">
        <div class="col-sm-8 offset-2">
            <div class="card card-dark">
                <div class="card-header">
                    <h3 class="card-title">Edit question</h3>
                </div>
                <div class="card-body">
                    <form method="post" action="{{route('questions.update', ['question'=>$question->id])  }}">
                        @method('patch')
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-12" >
                                <label for="question">Question:</label>
                                <input type="text" class="form-control" name="question" id="question" required="required" value="<?= $question->question ?>">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="question_type">Type:</label>
                                <select class="form-control" id="question_type" name="type">
                                    <option value="input">Input</option>
                                    <option value="select" <?= $question->type == 'select' ? 'selected' : '' ?>>Select</option>
                                    <option value="textarea" <?= $question->type == 'textarea' ? 'selected' : '' ?>>Textarea</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-row" id="question_select_group_div" <?= $question->type == 'select' ? '' : 'hidden' ?>>
                            <div class="form-group col-md-12">
                                <label for="question_select_group">Group:</label>
                                <select class="form-control" id="question_select_group" name="question_select_group_id" <?= $question->type == 'select' ? '' : 'disabled' ?>>
                                    @foreach($question_groups as $key => $value)
                                        <option value="<?= $value->id ?>"><?= $value->name ?></option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary float-right">Edit</button>
                        </div>
                    </form>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>
@endsection

src/resources/views/questions/edit_select_group.blade.php
@extends('layouts.master')

@section('content')
    <div class="row p-lg-2 pt-5">
        <div class="col-sm-12">
            <div class="card card-dark">
                <div class="card-header">
                    <h3 class="card-title">Report submission time</h3>
                </div>
                <form method="post" action="{{route('questions.update_question_select_group', ['question_select_group' => $question_group])  }}">
                @csrf
                @method('patch')
                    <div class="card-body">
                        <div class="form-row">
                            <div class="form-group col-md-12" >
                                <label for="question_group_name">Name:</label>
                                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="question_group_name" required="required" value="{{ $question_group->name }}">
                                @error('name')
                                <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="question_group_code">Code:</label>
                                <input type="text" class="form-control @error('code') is-invalid @enderror" name="code" id="question_group_code" required="required" value="{{ $question_group->code }}">
                                @error('code')
                                <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <hr>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-5">
                                <input type="text" class="form-control" id="question_select_name" placeholder="Label">
                            </div>
                            <div class="form-group col-md-5">
                                <input type="text" class="form-control" id="question_select_value" placeholder="Value">
                            </div>
                            <div class="form-group col-md-2">
                                <button class="btn btn-outline-primary" id="add_question_select" type="button">Add</button>
                            </div>
                        </div>
                        <div class="form-row"  id="add_question_selects_div">
                            <div class="form-group col-md-12">
                                <hr>
                            </div>
                        </div>
                        @foreach($question_selects as $key => $value)
                            <div class="form-row">
                                <div class="form-group col-md-5">
                                    <input type="text" class="form-control" value="{{ $value->name }}">
                                </div>
                                <div class="form-group col-md-5">
                                    <input type="text" class="form-control question-select-value" value="{{ $value->value }}">
                                </div>
                            </div>
                        @endforeach
                        <div class="form-row"  id="add_question_selects_div">
                            <div class="form-group col-md-12">
                                <hr>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary float-right">Update</button>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </form>
            </div>
        </div>
    </div>
@endsection

src/resources/views/questions/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="row">
        <div class="col-sm-6">
            <h2 class="align-items-center">Questions <span class="float-right" style="color: <?= $active_questions != 10 ? 'red' : 'green' ?>">(Active {{ $active_questions }})</span></h2>
            <table class="table jquery-datatable">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Question</th>
                    <th scope="col">Type</th>
                    <th scope="col">Group</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php $i = 1;  foreach($questions as $key => $value){ ?>
                <tr style="background-color: <?= $value->currently_active == 1 ? '' : 'lightcoral' ?>">
                    <td><?= $i ?></td>
                    <td><?= $value->question ?></td>
                    <td><?= $value->type ?></td>
                    <td><?= $value->name ? $value->name : '' ?></td>
                    <td><a class="btn btn-primary" href="{{ route('questions.edit', ['question' => $value->id]) }}">Edit</a></td>
                    <td>
                        <?php if ($value->currently_active == 0){ ?>
                            <button class="btn btn-primary" onclick="GlobalClass.ajaxDataseCall('{{ route('questions.activate_question')}}', {'id': '<?= $value->id ?>', '_token' : '<?= csrf_token() ?>'} )">Activate</button>
                        <?php }else { ?>
                            <form method="POST" action="{{ route('questions.destroy', ['question' => $value->id]) }}">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger delete-confirmation" type="button">Deactivate</button>
                            </form>

                        <?php } ?>
                    </td>
                </tr>
                <?php $i++; } ?>
                </tbody>
            </table>

        </div>
        <div class="col-sm-5 offset-1">
            <h2 class="align-content-center">Question groups</h2>
            <table class="table jquery-datatable">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Code</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                <?php $i = 1; foreach($question_groups as $key => $value){ ?>
                <tr>
                    <td><?= $i ?></td>
                    <td><?= $value->name ?></td>
                    <td><?= $value->code ?></td>
                    <td><a class="btn btn-primary" href="{{ route('questions.edit_select_group', ['question_select_group' => $value->id]) }}">Edit</a></td>
                </tr>
                <?php $i++; } ?>
                </tbody>
            </table>

        </div>

    </div>
@endsection